version: "3.8"
services:
    crop-recommendation-db:
        image: postgres:15
        restart: unless-stopped
        container_name: crop-recommendation-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            # - /var/lib/postgresql/data:/var/lib/postgresql/data
            - crop-recommendation:/var/lib/postgresql/data
    crop-recommendation-mongo:
        image: mongo
        restart: unless-stopped
        container_name: crop-recommendation-mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
            - "27017:27017"
        volumes:
            - crop-recommendation:/data/db

volumes:
    crop-recommendation:
